name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: cd opus-test && pod lib lint opus-test.podspec --verbose
